FROM debian:buster

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install mariadb-server -y;

COPY	conf/start.sh /start.sh
COPY	conf/my.cnf /etc/mysql/my.cnf
COPY    ./conf/wp_backup.sql ./

ENTRYPOINT    ["sh", "./start.sh"]

EXPOSE 3306